import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NotificationProvider } from "@/context/NotificationContext";
import NotificationContainer from "@/components/Notification";
import '@/app/globals.css'
import SideMenuBarEditor from "@/components/SideMenuBarEditor";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GyanShristi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   <div className="flex">
    <SideMenuBarEditor/>
    {children}
   </div>
  );
}
