import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "@/context/NotificationContext";
import NotificationContainer from "@/components/Notification";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Copyright from "@/components/mini-component/Copyright";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GyanShristi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NotificationProvider>
        <body>
          <NotificationContainer />
          <Navbar />
          {children}
          <Footer/>
          <Copyright />
        </body>
      </NotificationProvider>
    </html>
  );
}
