import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { NotificationProvider } from "@/context/NotificationContext";
import NotificationContainer from "@/components/Notification";
import { AuthProvider } from "@/context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "GyanShristi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <AuthProvider>
                <NotificationProvider>
                    <body>
                        <NotificationContainer />
                        {children}
                    </body>
                </NotificationProvider>
            </AuthProvider>
        </html>
    );
}
